### ISSUE TITLE
Devoir 7 - Prèsentation 19,23,25.05.2017

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [UPB-FILS/SE#66]
Présentation de micro ~~project~~ travaux - 5 à 10 (max) minutes chaque équipe, ceci vaut 20% de la note finale. La présentation est soutenue pendant le TD.Les point à traiter dans votre présentation:

1. Le site github de votre projet
2. Présentation de l'équipe: la composition, qui fait quoi.
3. La documentation que vous avez lu et le Wiki de votre projet
4. Le code et démo d'exécution

Pour la présentation vous pouvez utiliser: [Prezi](https://prezi.com/), [PowToon](https://www.powtoon.com), [Visme](https://www.visme.co/), ou vous pouvez créer votre présentation sur Google Docs ou One Drive ou iCloud ou Libre Office ou Open Office et la partager via [Slide Share](https://www.slideshare.net/) ou via le liens partagé si vous utilisez un site en cloud.

----

**Comment by isabelap** [comment]
Buna ziua,
Va rog sa-mi stergeti adresa de mail din acest grup.Va multumesc!
O zi buna,Isabela Puiu

**Comment by dragos-constantin-stoica** [comment]
Bună Isabela,

Nu mai este nimeni în echipa acestui repozitory, în afară de mine. Cel mai probabil ai subscris sau ai adăugat în lista de watch acest repozitory. [Aici](https://help.github.com/articles/about-notifications/) şi [aici](https://help.github.com/articles/managing-notifications/) sunt instrucţiuni cu mai multe detalii despre cum să te dezabonezi.
Dacă nu reuşeşti te rog să îmi spui şi mai caut soluţii.

Toate bune,
Dragoş
